//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/game_engine.proto
namespace tutorial2
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"game_output_info")]
  public partial class game_output_info : global::ProtoBuf.IExtensible
  {
    public game_output_info() {}
    

    private int _room_status = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"room_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int room_status
    {
      get { return _room_status; }
      set { _room_status = value; }
    }

    private tutorial2.ju_status _after = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"after", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tutorial2.ju_status after
    {
      get { return _after; }
      set { _after = value; }
    }
    private readonly global::System.Collections.Generic.List<tutorial2.game_input_info> _changes = new global::System.Collections.Generic.List<tutorial2.game_input_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"changes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.game_input_info> changes
    {
      get { return _changes; }
    }
  

    private tutorial2.money_change_list_unit _money_inout_list = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money_inout_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tutorial2.money_change_list_unit money_inout_list
    {
      get { return _money_inout_list; }
      set { _money_inout_list = value; }
    }

    private int _current_step = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"current_step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current_step
    {
      get { return _current_step; }
      set { _current_step = value; }
    }

    private bool _is_over = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"is_over", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_over
    {
      get { return _is_over; }
      set { _is_over = value; }
    }
    private readonly global::System.Collections.Generic.List<tutorial2.win_unit> _win_method = new global::System.Collections.Generic.List<tutorial2.win_unit>();
    [global::ProtoBuf.ProtoMember(8, Name=@"win_method", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.win_unit> win_method
    {
      get { return _win_method; }
    }
  

    private int _winner_point = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"winner_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winner_point
    {
      get { return _winner_point; }
      set { _winner_point = value; }
    }

    private int _winner_id = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"winner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winner_id
    {
      get { return _winner_id; }
      set { _winner_id = value; }
    }

    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }

    private int _seconds = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seconds
    {
      get { return _seconds; }
      set { _seconds = value; }
    }
    private readonly global::System.Collections.Generic.List<tutorial2.ready_to_start> _ready_list = new global::System.Collections.Generic.List<tutorial2.ready_to_start>();
    [global::ProtoBuf.ProtoMember(15, Name=@"ready_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.ready_to_start> ready_list
    {
      get { return _ready_list; }
    }
  
    private readonly global::System.Collections.Generic.List<tutorial2.user_info> _user_profile = new global::System.Collections.Generic.List<tutorial2.user_info>();
    [global::ProtoBuf.ProtoMember(16, Name=@"user_profile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.user_info> user_profile
    {
      get { return _user_profile; }
    }
  

    private int _ju_num = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"ju_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ju_num
    {
      get { return _ju_num; }
      set { _ju_num = value; }
    }

    private int _rtype = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"rtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rtype
    {
      get { return _rtype; }
      set { _rtype = value; }
    }

    private bool _code = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool code
    {
      get { return _code; }
      set { _code = value; }
    }

    private bool _msg = default(bool);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ju_status")]
  public partial class ju_status : global::ProtoBuf.IExtensible
  {
    public ju_status() {}
    
    private readonly global::System.Collections.Generic.List<tutorial2.player_dict> _player_list = new global::System.Collections.Generic.List<tutorial2.player_dict>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.player_dict> player_list
    {
      get { return _player_list; }
    }
  

    private int _point = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int point
    {
      get { return _point; }
      set { _point = value; }
    }

    private tutorial2.pai _fresh_drop_pai = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fresh_drop_pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tutorial2.pai fresh_drop_pai
    {
      get { return _fresh_drop_pai; }
      set { _fresh_drop_pai = value; }
    }

    private int _east_order = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"east_order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int east_order
    {
      get { return _east_order; }
      set { _east_order = value; }
    }

    private int _zhuang_num = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"zhuang_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zhuang_num
    {
      get { return _zhuang_num; }
      set { _zhuang_num = value; }
    }

    private int _win_limit = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"win_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int win_limit
    {
      get { return _win_limit; }
      set { _win_limit = value; }
    }

    private tutorial2.pai _zhufeng = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"zhufeng", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tutorial2.pai zhufeng
    {
      get { return _zhufeng; }
      set { _zhufeng = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _dice = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"dice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> dice
    {
      get { return _dice; }
    }
  

    private int _dui_pai_should_left = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"dui_pai_should_left", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dui_pai_should_left
    {
      get { return _dui_pai_should_left; }
      set { _dui_pai_should_left = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _ting_list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"ting_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> ting_list
    {
      get { return _ting_list; }
    }
  

    private int _last_dui_pai_position = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"last_dui_pai_position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int last_dui_pai_position
    {
      get { return _last_dui_pai_position; }
      set { _last_dui_pai_position = value; }
    }

    private int _quan_num = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"quan_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quan_num
    {
      get { return _quan_num; }
      set { _quan_num = value; }
    }

    private int _ju_num = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"ju_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ju_num
    {
      get { return _ju_num; }
      set { _ju_num = value; }
    }

    private int _current_step = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"current_step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current_step
    {
      get { return _current_step; }
      set { _current_step = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ready_to_start")]
  public partial class ready_to_start : global::ProtoBuf.IExtensible
  {
    public ready_to_start() {}
    

    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }

    private bool _ready = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ready", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ready
    {
      get { return _ready; }
      set { _ready = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"user_info")]
  public partial class user_info : global::ProtoBuf.IExtensible
  {
    public user_info() {}
    

    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }

    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }

    private string _photo_url = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"photo_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string photo_url
    {
      get { return _photo_url; }
      set { _photo_url = value; }
    }

    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }

    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }

    private int _card = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int card
    {
      get { return _card; }
      set { _card = value; }
    }

    private int _zuan = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"zuan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zuan
    {
      get { return _zuan; }
      set { _zuan = value; }
    }

    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private int _total_score_win = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"total_score_win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_score_win
    {
      get { return _total_score_win; }
      set { _total_score_win = value; }
    }

    private int _total_score_lose = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"total_score_lose", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_score_lose
    {
      get { return _total_score_lose; }
      set { _total_score_lose = value; }
    }

    private int _user_point = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"user_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_point
    {
      get { return _user_point; }
      set { _user_point = value; }
    }

    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }

    private string _session_id = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_dict")]
  public partial class player_dict : global::ProtoBuf.IExtensible
  {
    public player_dict() {}
    

    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }

    private int _user_point = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_point
    {
      get { return _user_point; }
      set { _user_point = value; }
    }

    private tutorial2.pai_list_dict _pai_list_dict = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pai_list_dict", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tutorial2.pai_list_dict pai_list_dict
    {
      get { return _pai_list_dict; }
      set { _pai_list_dict = value; }
    }
    private readonly global::System.Collections.Generic.List<tutorial2.remind_unit> _remind_list = new global::System.Collections.Generic.List<tutorial2.remind_unit>();
    [global::ProtoBuf.ProtoMember(4, Name=@"remind_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.remind_unit> remind_list
    {
      get { return _remind_list; }
    }
  
    private readonly global::System.Collections.Generic.List<tutorial2.remind_unit> _room_remind_list = new global::System.Collections.Generic.List<tutorial2.remind_unit>();
    [global::ProtoBuf.ProtoMember(5, Name=@"room_remind_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.remind_unit> room_remind_list
    {
      get { return _room_remind_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pai_list_dict")]
  public partial class pai_list_dict : global::ProtoBuf.IExtensible
  {
    public pai_list_dict() {}
    
    private readonly global::System.Collections.Generic.List<tutorial2.pai_list> _liang_pai = new global::System.Collections.Generic.List<tutorial2.pai_list>();
    [global::ProtoBuf.ProtoMember(1, Name=@"liang_pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.pai_list> liang_pai
    {
      get { return _liang_pai; }
    }
  
    private readonly global::System.Collections.Generic.List<tutorial2.pai> _qi_pai = new global::System.Collections.Generic.List<tutorial2.pai>();
    [global::ProtoBuf.ProtoMember(2, Name=@"qi_pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.pai> qi_pai
    {
      get { return _qi_pai; }
    }
  
    private readonly global::System.Collections.Generic.List<tutorial2.pai> _hand_pai = new global::System.Collections.Generic.List<tutorial2.pai>();
    [global::ProtoBuf.ProtoMember(3, Name=@"hand_pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.pai> hand_pai
    {
      get { return _hand_pai; }
    }
  
    private readonly global::System.Collections.Generic.List<tutorial2.pai> _zhuifeng_pai = new global::System.Collections.Generic.List<tutorial2.pai>();
    [global::ProtoBuf.ProtoMember(4, Name=@"zhuifeng_pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.pai> zhuifeng_pai
    {
      get { return _zhuifeng_pai; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"remind_unit")]
  public partial class remind_unit : global::ProtoBuf.IExtensible
  {
    public remind_unit() {}
    

    private string _remind_type = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"remind_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string remind_type
    {
      get { return _remind_type; }
      set { _remind_type = value; }
    }

    private tutorial2.pai _remind_pai = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"remind_pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tutorial2.pai remind_pai
    {
      get { return _remind_pai; }
      set { _remind_pai = value; }
    }
    private readonly global::System.Collections.Generic.List<tutorial2.ting_dict> _ting_dict_list = new global::System.Collections.Generic.List<tutorial2.ting_dict>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ting_dict_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.ting_dict> ting_dict_list
    {
      get { return _ting_dict_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ting_dict")]
  public partial class ting_dict : global::ProtoBuf.IExtensible
  {
    public ting_dict() {}
    

    private tutorial2.pai _pai_select_drop = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pai_select_drop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tutorial2.pai pai_select_drop
    {
      get { return _pai_select_drop; }
      set { _pai_select_drop = value; }
    }
    private readonly global::System.Collections.Generic.List<tutorial2.ting_score> _ting_score = new global::System.Collections.Generic.List<tutorial2.ting_score>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ting_score", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.ting_score> ting_score
    {
      get { return _ting_score; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ting_score")]
  public partial class ting_score : global::ProtoBuf.IExtensible
  {
    public ting_score() {}
    

    private tutorial2.pai _win_pai = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"win_pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tutorial2.pai win_pai
    {
      get { return _win_pai; }
      set { _win_pai = value; }
    }

    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"game_input_info")]
  public partial class game_input_info : global::ProtoBuf.IExtensible
  {
    public game_input_info() {}
    

    private string _action = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string action
    {
      get { return _action; }
      set { _action = value; }
    }

    private int _user_point = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_point
    {
      get { return _user_point; }
      set { _user_point = value; }
    }

    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }

    private int _room_num = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"room_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int room_num
    {
      get { return _room_num; }
      set { _room_num = value; }
    }

    private string _session_id = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"session_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string session_id
    {
      get { return _session_id; }
      set { _session_id = value; }
    }

    private tutorial2.pai _target_pai = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"target_pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tutorial2.pai target_pai
    {
      get { return _target_pai; }
      set { _target_pai = value; }
    }

    private int _current_step = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"current_step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int current_step
    {
      get { return _current_step; }
      set { _current_step = value; }
    }

    private bool _reverse = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"reverse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool reverse
    {
      get { return _reverse; }
      set { _reverse = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"win_unit")]
  public partial class win_unit : global::ProtoBuf.IExtensible
  {
    public win_unit() {}
    

    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }

    private string _method = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string method
    {
      get { return _method; }
      set { _method = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"money_change_unit")]
  public partial class money_change_unit : global::ProtoBuf.IExtensible
  {
    public money_change_unit() {}
    

    private int _user_point = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_point
    {
      get { return _user_point; }
      set { _user_point = value; }
    }

    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }

    private int _amount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"money_change_list_unit")]
  public partial class money_change_list_unit : global::ProtoBuf.IExtensible
  {
    public money_change_list_unit() {}
    

    private int _winner_point = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"winner_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winner_point
    {
      get { return _winner_point; }
      set { _winner_point = value; }
    }

    private int _winner_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"winner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winner_id
    {
      get { return _winner_id; }
      set { _winner_id = value; }
    }

    private int _loser_point = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"loser_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int loser_point
    {
      get { return _loser_point; }
      set { _loser_point = value; }
    }

    private int _loser_id = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"loser_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int loser_id
    {
      get { return _loser_id; }
      set { _loser_id = value; }
    }

    private int _amount = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pai_list")]
  public partial class pai_list : global::ProtoBuf.IExtensible
  {
    public pai_list() {}
    
    private readonly global::System.Collections.Generic.List<tutorial2.pai> _pai = new global::System.Collections.Generic.List<tutorial2.pai>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tutorial2.pai> pai
    {
      get { return _pai; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pai")]
  public partial class pai : global::ProtoBuf.IExtensible
  {
    public pai() {}
    

    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }

    private string _type = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}